### YamlMime:Yaml
ms.openlocfilehash: 0cca8cee75ac6aec27cd7bf31ab9fb4624b3688e
ms.sourcegitcommit: 85cb0bd5a71111e3f7b3af9fe02039857f9c1250
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 12/11/2020
ms.locfileid: "49661198"
inherit_from: .rubocop_todo.yml
AllCops:
  NewCops: enable
  Exclude:
  - bin/**/*
  - db/**/*
  - test/**/*
  - node_modules/**/*
Metrics/ModuleLength:
  CountAsOne:
  - array
  - hash
