### YamlMime:Yaml
ms.openlocfilehash: c681a33d70bfa1ea889aa7dbf439d31f09f705c1
ms.sourcegitcommit: 85cb0bd5a71111e3f7b3af9fe02039857f9c1250
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 12/11/2020
ms.locfileid: "49661205"
Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
  - config/environments/production.rb
Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
Metrics/AbcSize:
  Max: 18
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 30
Metrics/ModuleLength:
  Max: 209
Metrics/ParameterLists:
  Max: 7
Metrics/PerceivedComplexity:
  Max: 10
Style/Documentation:
  Exclude:
  - spec/**/*
  - app/controllers/auth_controller.rb
  - app/controllers/home_controller.rb
  - app/helpers/application_helper.rb
  - app/helpers/auth_helper.rb
  - app/helpers/calendar_helper.rb
  - app/helpers/home_helper.rb
  - app/models/application_record.rb
  - config/application.rb
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalStdStream:
  Exclude:
  - config/environments/production.rb
Style/HashSyntax:
  EnforcedStyle: hash_rockets
  Exclude:
  - Gemfile
  - app/mailers/application_mailer.rb
  - config/initializers/wrap_parameters.rb
Style/RedundantFetchBlock:
  Exclude:
  - config/puma.rb
Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names
Style/StringLiterals:
  Exclude:
  - config/environments/production.rb
  - config/puma.rb
Style/SymbolArray:
  EnforcedStyle: brackets
Layout/LineLength:
  Max: 190
